bold = true
color_mode = "ansi" # ansi, rgb or none
palette = "default" # default, darker, pastel or matrix
delay_ms = 20
inherit_style = false
kinds = ["curved"] # heavy, light, curved, knobby, emoji, outline, dots, blocks
num_pipes = 5
reset_threshold = 0.9 # 0.0–1.0
turn_chance = 0.15 # 0.0–1.0
